export const SITE_CONFIG = {
  name: "3F Ambulance",
  fullName: "3F AMBULANCE",
  tagline: "Transport Médical aux Trois Frontières",
  phone: "06 33 81 40 47",
  phoneDisplay: "06 33 81 40 47",
  phoneHref: "tel:+33633814047",
  whatsappHref: "https://wa.me/33633814047",
  email: "",
  domain: "https://3f-ambulance.fr",
  legalAddress: {
    street: "9 Allée de la Hardt",
    city: "Dietwiller",
    zip: "68440",
    country: "France",
  },
  publicLocation: "Saint-Louis (68) — Trois Frontières",
  serviceArea: "Saint-Louis et les Trois Frontières",
  siret: "",
  hours: "24h/24, 7j/7",
  services: [
    { name: "Ambulance", slug: "ambulance" },
    { name: "VSL", slug: "vsl" },
    { name: "Taxi Conventionné", slug: "taxi-conventionne" },
  ],
} as const;

export const COMMUNES_DESSERVIES = [
  "Saint-Louis",
  "Huningue",
  "Hésingue",
  "Blotzheim",
  "Bartenheim",
  "Village-Neuf",
  "Kembs",
  "Sierentz",
  "Rixheim",
  "Mulhouse",
  "Habsheim",
  "Rosenau",
  "Hégenheim",
  "Buschwiller",
  "Wentzwiller",
  "Attenschwiller",
  "Folgensbourg",
  "Hagenthal-le-Bas",
  "Hagenthal-le-Haut",
  "Leymen",
  "Neuwiller",
  "Ranspach-le-Bas",
  "Ranspach-le-Haut",
  "Stetten",
  "Bourgfelden",
] as const;

export const NAV_LINKS = [
  { label: "Accueil", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Zone d'intervention", href: "/zone-intervention" },
  { label: "À propos", href: "/a-propos" },
  { label: "FAQ", href: "/faq" },
  { label: "Contact", href: "/contact" },
] as const;
